<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Country Names in Portuguese
    |--------------------------------------------------------------------------
    |
    | Keyed by FIFA TLA code (3 letters). Fallbacks can be handled by
    | application code when the TLA is not present.
    |
    */
    'by_tla' => [
        'ARG' => 'Argentina',
        'ALG' => 'Argélia',
        'AUS' => 'Austrália',
        'AUT' => 'Áustria',
        'BEL' => 'Bélgica',
        'BIH' => 'Bósnia e Herzegovina',
        'BOL' => 'Bolívia',
        'BRA' => 'Brasil',
        'CAN' => 'Canadá',
        'CHI' => 'Chile',
        'COL' => 'Colômbia',
        'COD' => 'Congo (RD)',
        'CGO' => 'Congo (RD)',
        'CPV' => 'Cabo Verde',
        'CRC' => 'Costa Rica',
        'CRO' => 'Croácia',
        'CZE' => 'República Tcheca',
        'CUW' => 'Curaçao',
        'CUR' => 'Curaçao',
        'DEN' => 'Dinamarca',
        'ECU' => 'Equador',
        'EGY' => 'Egito',
        'ENG' => 'Inglaterra',
        'ESP' => 'Espanha',
        'FRA' => 'França',
        'GER' => 'Alemanha',
        'GHA' => 'Gana',
        'HAI' => 'Haiti',
        'IRN' => 'Irã',
        'IRQ' => 'Iraque',
        'ITA' => 'Itália',
        'CIV' => 'Costa do Marfim',
        'JPN' => 'Japão',
        'JOR' => 'Jordânia',
        'KOR' => 'Coreia do Sul',
        'MAR' => 'Marrocos',
        'MEX' => 'México',
        'NED' => 'Países Baixos',
        'NGA' => 'Nigéria',
        'NOR' => 'Noruega',
        'NZL' => 'Nova Zelândia',
        'PAN' => 'Panamá',
        'PAR' => 'Paraguai',
        'PER' => 'Peru',
        'POL' => 'Polônia',
        'POR' => 'Portugal',
        'QAT' => 'Catar',
        'KSA' => 'Arábia Saudita',
        'ROU' => 'Romênia',
        'RSA' => 'África do Sul',
        'SEN' => 'Senegal',
        'SCO' => 'Escócia',
        'SRB' => 'Sérvia',
        'SUI' => 'Suíça',
        'SWE' => 'Suécia',
        'TUN' => 'Tunísia',
        'TUR' => 'Turquia',
        'UKR' => 'Ucrânia',
        'URU' => 'Uruguai',
        'URY' => 'Uruguai',
        'USA' => 'Estados Unidos',
        'UZB' => 'Uzbequistão',
        'VEN' => 'Venezuela',
        'WAL' => 'País de Gales',
    ],
];
