<?php

return [
    'world_cup_2026' => [
        'ALG' => ['Algeria', 'ALG'],
        'ARG' => ['Argentina', 'ARG'],
        'AUS' => ['Australia', 'AUS'],
        'AUT' => ['Austria', 'AUT'],
        'BEL' => ['Belgium', 'BEL'],
        'BIH' => ['Bosnia-Herzegovina', 'Bosnia-H.', 'Bosnia & Herzegovina', 'Bosnia', 'BIH'],
        'BRA' => ['Brazil', 'BRA'],
        'CAN' => ['Canada', 'CAN'],
        'CPV' => ['Cape Verde Islands', 'Cape Verde', 'Cape-Verde-Islands', 'CPV'],
        'COL' => ['Colombia', 'COL'],
        'COD' => ['Congo DR', 'Congo-DR', 'COD', 'CGO'],
        'CRO' => ['Croatia', 'CRO'],
        'CUW' => ['Curaçao', 'Curacao', 'CUW', 'CUR'],
        'CZE' => ['Czechia', 'Czech Republic', 'Czech-Republic', 'CZE'],
        'ECU' => ['Ecuador', 'ECU'],
        'EGY' => ['Egypt', 'EGY'],
        'ENG' => ['England', 'ENG'],
        'FRA' => ['France', 'FRA'],
        'GER' => ['Germany', 'GER'],
        'GHA' => ['Ghana', 'GHA'],
        'HAI' => ['Haiti', 'HAI'],
        'IRN' => ['Iran', 'IRN'],
        'IRQ' => ['Iraq', 'IRQ'],
        'CIV' => ['Ivory Coast', 'Ivory-Coast', 'CIV'],
        'JPN' => ['Japan', 'JPN'],
        'JOR' => ['Jordan', 'JOR'],
        'MEX' => ['Mexico', 'MEX'],
        'MAR' => ['Morocco', 'MAR'],
        'NED' => ['Netherlands', 'NED'],
        'NZL' => ['New Zealand', 'New-Zealand', 'NZL'],
        'NOR' => ['Norway', 'NOR'],
        'PAN' => ['Panama', 'PAN'],
        'PAR' => ['Paraguay', 'PAR'],
        'POR' => ['Portugal', 'POR'],
        'QAT' => ['Qatar', 'QAT'],
        'KSA' => ['Saudi Arabia', 'Saudi-Arabia', 'KSA'],
        'SCO' => ['Scotland', 'SCO'],
        'SEN' => ['Senegal', 'SEN'],
        'RSA' => ['South Africa', 'South-Africa', 'RSA'],
        'KOR' => ['South Korea', 'Korea Republic', 'South-Korea', 'KOR'],
        'ESP' => ['Spain', 'ESP'],
        'SWE' => ['Sweden', 'SWE'],
        'SUI' => ['Switzerland', 'SUI'],
        'TUN' => ['Tunisia', 'TUN'],
        'TUR' => ['Turkey', 'Türkiye', 'Turkiye', 'TUR'],
        'USA' => ['United States', 'USA'],
        'URU' => ['Uruguay', 'URU', 'URY'],
        'UZB' => ['Uzbekistan', 'UZB'],
    ],

    'clubs' => [
        'ATLETICO_MG' => ['Atletico MG', 'Atletico Mineiro', 'CA Mineiro', 'Mineiro'],
        'ATLETICO_PR' => ['Atletico Paranaense', 'CA Paranaense', 'CAP', 'Athletico PR', 'Athletico Paranaense'],
        'BAHIA' => ['Bahia', 'EC Bahia'],
        'BOTAFOGO' => ['Botafogo', 'Botafogo FR'],
        'CHAPECOENSE' => ['Chapecoense', 'Chapecoense SC', 'Chapecoense AF'],
        'CORINTHIANS' => ['Corinthians', 'SC Corinthians Paulista', 'Corinthians Paulista'],
        'CORITIBA' => ['Coritiba', 'Coritiba FBC'],
        'CRUZEIRO' => ['Cruzeiro', 'Cruzeiro EC'],
        'FLAMENGO' => ['Flamengo', 'CR Flamengo'],
        'FLUMINENSE' => ['Fluminense', 'Fluminense FC'],
        'GREMIO' => ['Gremio', 'Gremio FBPA'],
        'INTERNACIONAL' => ['Internacional', 'SC Internacional'],
        'MIRASSOL' => ['Mirassol', 'Mirassol FC'],
        'PALMEIRAS' => ['Palmeiras', 'SE Palmeiras'],
        'RB_BRAGANTINO' => ['RB Bragantino', 'Red Bull Bragantino', 'Bragantino'],
        'REMO' => ['Remo', 'Clube do Remo'],
        'SANTOS' => ['Santos', 'Santos FC'],
        'SAO_PAULO' => ['Sao Paulo', 'Sao Paulo FC'],
        'VASCO' => ['Vasco da Gama', 'CR Vasco da Gama', 'Vasco'],
        'VITORIA' => ['Vitoria', 'EC Vitoria'],
    ],
];
